name: get latest xiaoya alist
on:
  workflow_dispatch:
jobs:
  just-tset:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          docker run -d -p 5678:80 -v /home/runner/work/xylist/xylist/alist:/opt/alist/alist --name=xiaoya xiaoyaliu/alist:latest && docker ps -a
          docker ps -a
          sleep 1m
          pwd
          ls -al