name: sync xiaoya
on:
  workflow_dispatch:
jobs:
  just-tset:
    runs-on: ubuntu-latest
    steps:
      - name: copy
        run: |
          docker run -d --name=xiaoya xiaoyaliu/alist:latest
          sleep 30s
          docker cp  xiaoya:/opt/alist/alist ./xylist
          ls -al 