name: sync xiaoya
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  sync-xiaoya:
    runs-on: ubuntu-latest
    steps:
      - name: copy
        run: |
          docker run -d --name=xiaoya xiaoyaliu/alist:latest
          sleep 30s
          mkdir data
          docker cp xiaoya:/opt/alist/alist ./data/
          docker cp xiaoya:/var/lib/data.zip ./data/
          tar -czvf data.tar.gz ./data
          cd ./data
          chmod +x alist
          ./alist
      - name: upload data
        run: |
          git clone https://${{ secrets.PAT }}@github.com/purepoorx/xylist.git
          cd xylist
          git config user.name robot
          git config user.email robot@mail.com
          cp -f ./../data.tar.gz ./
          git add data.tar.gz
          git commit -m "Upload Via Github Actions, $(date "+%Y/%m/%d")"
          git push
